experiment-name: "M_javanica"
genome: "/home/531734/mike/javanica/javanica_assemblies/M_javanica_062022.final.samba.scaffolds.sorted.renamed.fasta"
flnc_bam: "/home/531734/mike/javanica/data/IsoSeq_2021/flnc.bam"
